name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: golang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19"
          cache: true
          cache-dependency-path: golang/go.sum

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Build Go binary
        run: go build -o tyk-sre-assignment .

      - name: Build Docker image
        run: docker build -t tyk-sre-assignment .